import { type ImageSourcePropType } from "react-native";

export const optimizedMenuImageAssets: Record<string, ImageSourcePropType> = {
  "afghani-chicken-Combo.jpg": require("../assets/menu-optimized/afghani-chicken-Combo.jpg"),
  "Aloo Dum Combo.jpg": require("../assets/menu-optimized/Aloo Dum Combo.jpg"),
  "aloo-bhaja (1).jpg": require("../assets/menu-optimized/aloo-bhaja (1).jpg"),
  "aloo-bhaja.jpg": require("../assets/menu-optimized/aloo-bhaja.jpg"),
  "aloo-Paratha.avif": require("../assets/menu-optimized/aloo-Paratha.avif"),
  "atta-Laccha-paratha.jpeg": require("../assets/menu-optimized/atta-Laccha-paratha.jpeg"),
  "Atta-tandoori-Roti.jpg": require("../assets/menu-optimized/Atta-tandoori-Roti.jpg"),
  "Baby-corn-chili.jpg": require("../assets/menu-optimized/Baby-corn-chili.jpg"),
  "Baby-Corn-Manchurian.jpg": require("../assets/menu-optimized/Baby-Corn-Manchurian.jpg"),
  "Butter-Naan.jpeg": require("../assets/menu-optimized/Butter-Naan.jpeg"),
  "Butter-Roti.jpeg": require("../assets/menu-optimized/Butter-Roti.jpeg"),
  "Butter-Tandori-Roti.png": require("../assets/menu-optimized/Butter-Tandori-Roti.webp"),
  "chana-masala (1).jpg": require("../assets/menu-optimized/chana-masala (1).jpg"),
  "chana-masala.jpg": require("../assets/menu-optimized/chana-masala.jpg"),
  "chicken 65_69.jpg": require("../assets/menu-optimized/chicken 65_69.jpg"),
  "chicken Afghani.jpg": require("../assets/menu-optimized/chicken Afghani.jpg"),
  "chicken black pepper.webp": require("../assets/menu-optimized/chicken black pepper.webp"),
  "Chicken butter masala combo.jpg": require("../assets/menu-optimized/Chicken butter masala combo.jpg"),
  "Chicken Butter Masala.avif": require("../assets/menu-optimized/Chicken Butter Masala.avif"),
  "chicken Cheese.jpg": require("../assets/menu-optimized/chicken Cheese.jpg"),
  "chicken cutlet.jpg": require("../assets/menu-optimized/chicken cutlet.jpg"),
  "Chicken Do Pyaza.jpg": require("../assets/menu-optimized/Chicken Do Pyaza.jpg"),
  "chicken finger.jpg": require("../assets/menu-optimized/chicken finger.jpg"),
  "chicken malai curry.jpg": require("../assets/menu-optimized/chicken malai curry.jpg"),
  "chicken Pakoda.png": require("../assets/menu-optimized/chicken Pakoda.webp"),
  "chicken Roll.jpg": require("../assets/menu-optimized/chicken Roll.jpg"),
  "chicken schezwan.webp": require("../assets/menu-optimized/chicken schezwan.webp"),
  "Chicken tadka.jpg": require("../assets/menu-optimized/Chicken tadka.jpg"),
  "Chicken Tikka Butter Masala.jpg": require("../assets/menu-optimized/Chicken Tikka Butter Masala.jpg"),
  "Chicken tikka Kebab.jpg": require("../assets/menu-optimized/Chicken tikka Kebab.jpg"),
  "Chicken-Bharta-Combo.jpeg": require("../assets/menu-optimized/Chicken-Bharta-Combo.jpeg"),
  "Chicken-Bharta.jpg": require("../assets/menu-optimized/Chicken-Bharta.jpg"),
  "Chicken-Fried Rice.jpeg": require("../assets/menu-optimized/Chicken-Fried Rice.jpeg"),
  "chicken-handi-biryani.jpg": require("../assets/menu-optimized/chicken-handi-biryani.jpg"),
  "Chicken-Korma-combo.webp": require("../assets/menu-optimized/Chicken-Korma-combo.webp"),
  "chicken-korma.jpg": require("../assets/menu-optimized/chicken-korma.jpg"),
  "Chicken-Malai.jpg": require("../assets/menu-optimized/Chicken-Malai.jpg"),
  "chicken-noodles.jpg": require("../assets/menu-optimized/chicken-noodles.jpg"),
  "Chicken-thali.jpeg": require("../assets/menu-optimized/Chicken-thali.jpeg"),
  "Chili Panner Combo(Paratha).png": require("../assets/menu-optimized/Chili Panner Combo(Paratha).webp"),
  "CHILI-chicken-combo.jpg": require("../assets/menu-optimized/CHILI-chicken-combo.jpg"),
  "Chilli-Chicken.jpg": require("../assets/menu-optimized/Chilli-Chicken.jpg"),
  "chilli-mushroom.jpg": require("../assets/menu-optimized/chilli-mushroom.jpg"),
  "chilli-paneer.jpg": require("../assets/menu-optimized/chilli-paneer.jpg"),
  "Curry-chawal.jpg": require("../assets/menu-optimized/Curry-chawal.jpg"),
  "D-egg-Chi-Roll.jpg": require("../assets/menu-optimized/D-egg-Chi-Roll.jpg"),
  "Dal-Tadka (1).jpg": require("../assets/menu-optimized/Dal-Tadka (1).jpg"),
  "Dal-Tadka-Butter (1).jpg": require("../assets/menu-optimized/Dal-Tadka-Butter (1).jpg"),
  "Dal-Tadka-Butter.jpg": require("../assets/menu-optimized/Dal-Tadka-Butter.jpg"),
  "Dal-Tadka-combo.jpg": require("../assets/menu-optimized/Dal-Tadka-combo.jpg"),
  "Dal-Tadka.jpg": require("../assets/menu-optimized/Dal-Tadka.jpg"),
  "Dhaniya chicken.webp": require("../assets/menu-optimized/Dhaniya chicken.webp"),
  "Dhaniya_Rezala Chicken Combo.jpg": require("../assets/menu-optimized/Dhaniya_Rezala Chicken Combo.jpg"),
  "Double-egg-Curry.webp": require("../assets/menu-optimized/Double-egg-Curry.webp"),
  "Egg Chicken roll.jpg": require("../assets/menu-optimized/Egg Chicken roll.jpg"),
  "Egg Chicken tadka.jpg": require("../assets/menu-optimized/Egg Chicken tadka.jpg"),
  "Egg Fried RICE.jpg": require("../assets/menu-optimized/Egg Fried RICE.jpg"),
  "Egg_Handi_B.jpg": require("../assets/menu-optimized/Egg_Handi_B.jpg"),
  "Egg-Bhurji.jpg": require("../assets/menu-optimized/Egg-Bhurji.jpg"),
  "Egg-Chicken_Nodd.jpg": require("../assets/menu-optimized/Egg-Chicken_Nodd.jpg"),
  "Egg-Fried-Noodles.webp": require("../assets/menu-optimized/Egg-Fried-Noodles.webp"),
  "egg-roll.jpg": require("../assets/menu-optimized/egg-roll.jpg"),
  "Egg-Tadka-Combo.jpeg": require("../assets/menu-optimized/Egg-Tadka-Combo.jpeg"),
  "Egg-Tadka.jpg": require("../assets/menu-optimized/Egg-Tadka.jpg"),
  "Egg-thali.jpeg": require("../assets/menu-optimized/Egg-thali.jpeg"),
  "Family_pack_Birayni.avif": require("../assets/menu-optimized/Family_pack_Birayni.avif"),
  "Fish Fry.jpg": require("../assets/menu-optimized/Fish Fry.jpg"),
  "Fish Thali.webp": require("../assets/menu-optimized/Fish Thali.webp"),
  "Fish-Combo.jpeg": require("../assets/menu-optimized/Fish-Combo.jpeg"),
  "Fish-Fingers.jpg": require("../assets/menu-optimized/Fish-Fingers.jpg"),
  "French-Fries.jpg": require("../assets/menu-optimized/French-Fries.jpg"),
  "Fried rice combo(Chili Panner).png": require("../assets/menu-optimized/Fried rice combo(Chili Panner).webp"),
  "Garlic_Naan-.jpg": require("../assets/menu-optimized/Garlic_Naan-.jpg"),
  "Garlic-Panner.jpg": require("../assets/menu-optimized/Garlic-Panner.jpg"),
  "gatte-Ki-Sabji (1).jpg": require("../assets/menu-optimized/gatte-Ki-Sabji (1).jpg"),
  "gatte-Ki-Sabji.jpg": require("../assets/menu-optimized/gatte-Ki-Sabji.jpg"),
  "Green-Salad.jpg": require("../assets/menu-optimized/Green-Salad.jpg"),
  "Handi Mutton.jpg": require("../assets/menu-optimized/Handi Mutton.jpg"),
  "handi paneer masala combo.png": require("../assets/menu-optimized/handi paneer masala combo.webp"),
  "Handi_Mutton.jpg": require("../assets/menu-optimized/Handi_Mutton.jpg"),
  "Handi-Chicken.png": require("../assets/menu-optimized/Handi-Chicken.webp"),
  "Handi-Mutton-Combo.jpeg": require("../assets/menu-optimized/Handi-Mutton-Combo.jpeg"),
  "jeera rice.jpeg": require("../assets/menu-optimized/jeera rice.jpeg"),
  "Kabab-Roll.jpg": require("../assets/menu-optimized/Kabab-Roll.jpg"),
  "Kadai-Chicken.jpg": require("../assets/menu-optimized/Kadai-Chicken.jpg"),
  "kadai-mushroom-recipe (1).jpg": require("../assets/menu-optimized/kadai-mushroom-recipe (1).jpg"),
  "kadai-mushroom-recipe.jpg": require("../assets/menu-optimized/kadai-mushroom-recipe.jpg"),
  "kadai-paneer (1).jpg": require("../assets/menu-optimized/kadai-paneer (1).jpg"),
  "kadai-paneer.jpg": require("../assets/menu-optimized/kadai-paneer.jpg"),
  "Kashmiri-Dum-Aloo (1).jpg": require("../assets/menu-optimized/Kashmiri-Dum-Aloo (1).jpg"),
  "Kashmiri-Dum-Aloo.jpg": require("../assets/menu-optimized/Kashmiri-Dum-Aloo.jpg"),
  "Kashmiri-Pulao.jpg": require("../assets/menu-optimized/Kashmiri-Pulao.jpg"),
  "Lachha-Paratha.jpg": require("../assets/menu-optimized/Lachha-Paratha.jpg"),
  "litti murga.jpg": require("../assets/menu-optimized/litti murga.jpg"),
  "Litti-chokha.webp": require("../assets/menu-optimized/Litti-chokha.webp"),
  "liver_fry.jpg": require("../assets/menu-optimized/liver_fry.jpg"),
  "Masala-Kulcha.webp": require("../assets/menu-optimized/Masala-Kulcha.webp"),
  "Masala-papad.jpg": require("../assets/menu-optimized/Masala-papad.jpg"),
  "Matar panner Masala combo.avif": require("../assets/menu-optimized/Matar panner Masala combo.avif"),
  "Matar-Mashroom-Masala (1).jpeg": require("../assets/menu-optimized/Matar-Mashroom-Masala (1).jpeg"),
  "Matar-Mashroom-Masala.jpeg": require("../assets/menu-optimized/Matar-Mashroom-Masala.jpeg"),
  "Mixed Noddles.webp": require("../assets/menu-optimized/Mixed Noddles.webp"),
  "Mixed-Fried-Rice.webp": require("../assets/menu-optimized/Mixed-Fried-Rice.webp"),
  "mixed-veg (1).jpg": require("../assets/menu-optimized/mixed-veg (1).jpg"),
  "mixed-veg.jpg": require("../assets/menu-optimized/mixed-veg.jpg"),
  "Mush-Do-P (1).jpeg": require("../assets/menu-optimized/Mush-Do-P (1).jpeg"),
  "Mush-Do-P.jpeg": require("../assets/menu-optimized/Mush-Do-P.jpeg"),
  "Mushroom Butter-M (1).jpg": require("../assets/menu-optimized/Mushroom Butter-M (1).jpg"),
  "Mushroom Butter-M.jpg": require("../assets/menu-optimized/Mushroom Butter-M.jpg"),
  "Mushroom fried rice.jpeg": require("../assets/menu-optimized/Mushroom fried rice.jpeg"),
  "Mushroom Roll.jpg": require("../assets/menu-optimized/Mushroom Roll.jpg"),
  "mushroom_manchurian.avif": require("../assets/menu-optimized/mushroom_manchurian.avif"),
  "mushroom-fry.jpg": require("../assets/menu-optimized/mushroom-fry.jpg"),
  "Mushroom-Noodle.webp": require("../assets/menu-optimized/Mushroom-Noodle.webp"),
  "mushroom-thali.jpg": require("../assets/menu-optimized/mushroom-thali.jpg"),
  "mutter-mushroom (1).jpg": require("../assets/menu-optimized/mutter-mushroom (1).jpg"),
  "mutter-mushroom.jpg": require("../assets/menu-optimized/mutter-mushroom.jpg"),
  "mutton_Handi_B.jpg": require("../assets/menu-optimized/mutton_Handi_B.jpg"),
  "Mutton_Litti.jpg": require("../assets/menu-optimized/Mutton_Litti.jpg"),
  "mutton-thali.avif": require("../assets/menu-optimized/mutton-thali.avif"),
  "Noodles combo(chili Panner).png": require("../assets/menu-optimized/Noodles combo(chili Panner).webp"),
  "Pabda-Thali.jpeg": require("../assets/menu-optimized/Pabda-Thali.jpeg"),
  "palak_panner masal combo.jpg": require("../assets/menu-optimized/palak_panner masal combo.jpg"),
  "palak-Panner (1).jpeg": require("../assets/menu-optimized/palak-Panner (1).jpeg"),
  "palak-Panner.jpeg": require("../assets/menu-optimized/palak-Panner.jpeg"),
  "paneer-butter-masala (1).jpg": require("../assets/menu-optimized/paneer-butter-masala (1).jpg"),
  "paneer-butter-masala.jpg": require("../assets/menu-optimized/paneer-butter-masala.jpg"),
  "paneer-do-pyaza (1).jpg": require("../assets/menu-optimized/paneer-do-pyaza (1).jpg"),
  "paneer-do-pyaza.jpg": require("../assets/menu-optimized/paneer-do-pyaza.jpg"),
  "paneer-fried-rice.webp": require("../assets/menu-optimized/paneer-fried-rice.webp"),
  "paneer-manchurian.jpg": require("../assets/menu-optimized/paneer-manchurian.jpg"),
  "Paneer-Masala.jpg": require("../assets/menu-optimized/Paneer-Masala.jpg"),
  "paneer-pakoda.jpg": require("../assets/menu-optimized/paneer-pakoda.jpg"),
  "paneer-pasanda.jpg": require("../assets/menu-optimized/paneer-pasanda.jpg"),
  "paneer-tikka.jpg": require("../assets/menu-optimized/paneer-tikka.jpg"),
  "panner-Bharta (1).jpg": require("../assets/menu-optimized/panner-Bharta (1).jpg"),
  "panner-Bharta.jpg": require("../assets/menu-optimized/panner-Bharta.jpg"),
  "Panner-Bhujiya.jpg": require("../assets/menu-optimized/Panner-Bhujiya.jpg"),
  "panner-butter-combo.webp": require("../assets/menu-optimized/panner-butter-combo.webp"),
  "Panner-Malai-Kofta (1).jpg": require("../assets/menu-optimized/Panner-Malai-Kofta (1).jpg"),
  "Panner-Malai-Kofta.jpg": require("../assets/menu-optimized/Panner-Malai-Kofta.jpg"),
  "Panner-noddles.jpeg": require("../assets/menu-optimized/Panner-noddles.jpeg"),
  "panner-paratha.jpg": require("../assets/menu-optimized/panner-paratha.jpg"),
  "panner-Roll.jpeg": require("../assets/menu-optimized/panner-Roll.jpeg"),
  "panner-thali.jpeg": require("../assets/menu-optimized/panner-thali.jpeg"),
  "plain rice Basmati .jpg": require("../assets/menu-optimized/plain rice Basmati .jpg"),
  "plain-naan.jpeg": require("../assets/menu-optimized/plain-naan.jpeg"),
  "prawn masala combo.jpg": require("../assets/menu-optimized/prawn masala combo.jpg"),
  "prawn-fried-rice.webp": require("../assets/menu-optimized/prawn-fried-rice.webp"),
  "Prawn-Noddle.jpg": require("../assets/menu-optimized/Prawn-Noddle.jpg"),
  "prawn-thali.jpg": require("../assets/menu-optimized/prawn-thali.jpg"),
  "rajma-chawal.jpg": require("../assets/menu-optimized/rajma-chawal.jpg"),
  "Reshmi Kabab.jpeg": require("../assets/menu-optimized/Reshmi Kabab.jpeg"),
  "Schezwan Chicken Fried Rice.jpg": require("../assets/menu-optimized/Schezwan Chicken Fried Rice.jpg"),
  "Schezwan veg fried rice.webp": require("../assets/menu-optimized/Schezwan veg fried rice.webp"),
  "Schezwan-Egg-Fried-Rice-.jpg": require("../assets/menu-optimized/Schezwan-Egg-Fried-Rice-.jpg"),
  "Schezwan-Mixed -Noodles.jpeg": require("../assets/menu-optimized/Schezwan-Mixed -Noodles.jpeg"),
  "Schezwan-Noodles-.webp": require("../assets/menu-optimized/Schezwan-Noodles-.webp"),
  "Schezwan-Noodles-chicken.jpeg": require("../assets/menu-optimized/Schezwan-Noodles-chicken.jpeg"),
  "Schezwan-Noodles-Egg.webp": require("../assets/menu-optimized/Schezwan-Noodles-Egg.webp"),
  "Schezwan-Noodles-Egg+C.jpeg": require("../assets/menu-optimized/Schezwan-Noodles-Egg+C.jpeg"),
  "Schezwan-Noodles-mushroom.jpeg": require("../assets/menu-optimized/Schezwan-Noodles-mushroom.jpeg"),
  "Schezwan-Noodles-panner.jpeg": require("../assets/menu-optimized/Schezwan-Noodles-panner.jpeg"),
  "Schezwan-Noodles-Prawn.jpeg": require("../assets/menu-optimized/Schezwan-Noodles-Prawn.jpeg"),
  "Schezwan-Noodles-prawn.jpg": require("../assets/menu-optimized/Schezwan-Noodles-prawn.jpg"),
  "szechuan-chicken-.jpg": require("../assets/menu-optimized/szechuan-chicken-.jpg"),
  "Tandoori-Chicken.jpg": require("../assets/menu-optimized/Tandoori-Chicken.jpg"),
  "Tandoori-Roti.jpeg": require("../assets/menu-optimized/Tandoori-Roti.jpeg"),
  "Tangdi-kebab.webp": require("../assets/menu-optimized/Tangdi-kebab.webp"),
  "tawa-roti.jpeg": require("../assets/menu-optimized/tawa-roti.jpeg"),
  "Thali-Chicken-COMBO.avif": require("../assets/menu-optimized/Thali-Chicken-COMBO.avif"),
  "Veg manchurian Combo.jpg": require("../assets/menu-optimized/Veg manchurian Combo.jpg"),
  "Veg_manchuriyan.jpg": require("../assets/menu-optimized/Veg_manchuriyan.jpg"),
  "veg-Ball.webp": require("../assets/menu-optimized/veg-Ball.webp"),
  "Veg-Cutlet.jpg": require("../assets/menu-optimized/Veg-Cutlet.jpg"),
  "veg-fried-rice.jpg": require("../assets/menu-optimized/veg-fried-rice.jpg"),
  "veg-nodd.jpg": require("../assets/menu-optimized/veg-nodd.jpg"),
  "Veg-Thali.jpg": require("../assets/menu-optimized/Veg-Thali.jpg"),
  "Yellow Dal Fry Combo.jpg": require("../assets/menu-optimized/Yellow Dal Fry Combo.jpg"),
};
